2 ДЗ (index и catalog html)
htmlacademy-htmlcss/996491-nerds-31 pull request #2
Opened 2021-05-24 15:37 UTC by Bakitov-Tilegen

Разметка index и catalog html
Как мне сделать слайдер в индексе ? ))) ul>li>a???

2021-05-25 10:58 UTC, mikhin commented
@Bakitov-Tilegen Где бы тебе было удобнее общаться? Можем например во Вконтакте (https://vk.com/ymikhin) или в Телеграме (https://t.me/ymikhin).

2021-05-26 07:25 UTC, mikhin commented
`scss/style.scss `

@Bakitov-Tilegen , на этом потоке не используются препроцессоры)

2021-05-26 07:25 UTC, mikhin requested changes

2021-05-26 07:25 UTC, mikhin commented on catalog.html
> +    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
В рабочих проектах шрифты лучше грузить локально — так быстрее)

2021-05-26 07:25 UTC, mikhin commented on catalog.html
> +        <a href="./index.html" class="header-logo"><img src="./img/header/nerds-logo.svg" alt="Логотип Нердс" width="160" height="65"></a>
Путь с точкой в начале это относительный путь, относительно текущей страницы. Это почти всегда менее удобно чем абсолютный путь. Абсолютный путь — путь от корня сайта, начинается со `/`.

Давай везде исправим на абсолютные пути?)

2021-05-26 07:25 UTC, mikhin commented on catalog.html
> +      <section class="header-wrapper">
section — это контентный раздел. Прям такой контент за которым пользователь специально пришел и потребляет его с жадностью и удовольствием) Типа как глава книги, отдельная) Всякие интерфейсные штуки, типа шапки — это не контент, за которым пришел пользователь, поэтому этот тег тут неуместен)

Не бойся использовать `div`)

2021-05-26 07:25 UTC, mikhin commented on catalog.html
> +      <section class="header-wrapper">
Это касается всех section в текущей разметке обоих страниц, давай еще раз по всем ним пройдемся и внимательно над каждым подумаем)

2021-05-26 07:25 UTC, mikhin commented on catalog.html
> +            <h2 class="header-title">Магазин готовых шаблонов</h2>
Скорее всего это заголовок первого уровня)

2021-05-26 07:25 UTC, mikhin commented on catalog.html
> +                <input type="radio" name="radio" id="radio-adaptive">
атрибут name должен означать какой-то контентный текущий смысл этих радио-кнопок)

2021-05-26 07:25 UTC, mikhin commented on catalog.html
> +                <input type="checkbox" name="checkbox" id="checkbox-slider" checked>
атрибут name должен означать какой-то контентный текущий смысл этих чекбоксов)

2021-05-26 07:25 UTC, mikhin commented on catalog.html
> +                <button type="submit" class="btn btn--gray sort-btn">Показать</button>
btn > button

лучше не сокращать, т.к. сильно мы не экономим, а читабельность кода падает прям сильно)

2021-05-26 07:25 UTC, mikhin commented on catalog.html
> +                <li class="result-item"><a href="#" class="result-link"><img src="#" alt="Седона Сайт по бронированию"></a></li>
У каждой карточки есть еще заголовок, описание и ссылка)

2021-05-26 07:25 UTC, mikhin commented on catalog.html
> +          <h3 class="address-title">NЁRDS DESIGN STUDIO</h3>
Нужно написать строчными с заглавной, а уже потом в CSS стилизовать как нужно)

2021-05-26 07:25 UTC, mikhin commented on index.html
> +        <h1 class="vissible-title">Услуги</h1>
vissible > visible

2021-05-26 07:25 UTC, mikhin commented on index.html
> +          <ul class="slider-list">
Сейчас тут не совсем верно передана структура слайдера. Каждый слайд — это самостоятельный блок, у которого есть своё изображение и свои текстовые данные, который просто помещен в список слайдов. По идее можно взять эти все слайды и по отдельности поместить в разные места сайта и все должно работать)

2021-05-26 07:25 UTC, mikhin commented on index.html
> +        <h1 class="vissible-title slider-title">Преимущества</h1>
Я не совсем уверен что h1 всей страницы должен относиться именно к слайдеру и иметь такое содержание)

2021-05-26 07:25 UTC, mikhin commented on index.html
> +                <a href="" class="btn btn--red service-link">Заказать</a>
href не должен быть пустым)

2021-05-26 07:25 UTC, mikhin commented on index.html
> +        <h1 class="vissible-title">О нас</h1>
Хоть это и не запрещено спецификацией, но все же считается что h1 должен быть один на странице, и выше уже есть h1)

2021-05-26 07:25 UTC, mikhin commented on index.html
> +        <span class="about-us-title">Мы — маленькая, но гордая </br> дизайн-студия из Краснодара.</span>
Давай пока уберем `<br>`? Позже попробуем стилизовать через CSS)

2021-05-26 07:25 UTC, mikhin commented on index.html
> +          <li class="about-us-item">	Веб-сайтов любой сложности</li>
Пробел после открывающего тега — лишний)

2021-05-26 07:25 UTC, mikhin commented on index.html
> +        <table class="about-us-signin">
Тут скорее не совсем таблица. Посмотри в сторону списка описаний https://htmlacademy.ru/courses/301/run/6

2021-05-26 07:25 UTC, mikhin commented on index.html
> +          <li class="client-item"><a href="https://htmlacademy.ru/"><img src="./img/main/client-1.svg" alt="htmlacademy клиент"></a></li>
давай сделаем alt более полезными)

2021-05-26 11:56 UTC, Bakitov-Tilegen commented on catalog.html
> +    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
окей спасибо ☺️ 😉 😊 😍 🙏

2021-05-26 11:57 UTC, Bakitov-Tilegen commented on catalog.html
> +        <a href="./index.html" class="header-logo"><img src="./img/header/nerds-logo.svg" alt="Логотип Нердс" width="160" height="65"></a>
😳  не знал 0_0 )))

2021-05-26 12:01 UTC, Bakitov-Tilegen commented on catalog.html
> +                <input type="radio" name="radio" id="radio-adaptive">
👌

2021-05-26 12:03 UTC, Bakitov-Tilegen commented on index.html
> +        <span class="about-us-title">Мы — маленькая, но гордая </br> дизайн-студия из Краснодара.</span>
окей)))

2021-05-26 12:05 UTC, Bakitov-Tilegen commented on index.html
> +          <li class="about-us-item">	Веб-сайтов любой сложности</li>
👌

2021-05-26 16:45 UTC, Bakitov-Tilegen commented on index.html
> +        <table class="about-us-signin">
ok

2021-05-26 16:57 UTC, Bakitov-Tilegen commented on index.html
> +          <li class="client-item"><a href="https://htmlacademy.ru/"><img src="./img/main/client-1.svg" alt="htmlacademy клиент"></a></li>
Ок

2021-05-29 17:52 UTC, mikhin commented
@Bakitov-Tilegen , переоткрываю этот ПР, так как изначально обсуждение началось в нем)

2021-05-29 17:58 UTC, mikhin requested changes

2021-05-29 17:58 UTC, mikhin commented on catalog.html
> +                <ul class="sort-hedaer-list">
опечатка в слове header

2021-05-29 17:58 UTC, mikhin commented on catalog.html
> +                <h3 class="sort-header-title">Стоимость:</h3>
Не очень понятно почему заголовок стоимость называется классом `sort-header-title` — он ведь не относится к сортировке, а относится к фильтру)

2021-05-29 17:58 UTC, mikhin commented on catalog.html
> +                    <li class="sort-header-item">По типу</li>
Тут тоже нужные какие-то интерактивные элементы)

2021-05-29 17:58 UTC, mikhin commented on catalog.html
> +                        <legend></legend>
Или нужно убрать пустой тег, или вписать в него какой-то контент)

2021-05-29 17:58 UTC, mikhin commented on catalog.html
> +                        <p>
Если нужны обертки или контейнеры, то пусть это лучше будет div, чем абзац)

2021-05-29 17:58 UTC, mikhin commented on catalog.html
> +                        <legend><h3 class="radio-title">Сетка:</h3></legend>
Если это легенда, то уже заголовок не нужен)

2021-05-29 17:58 UTC, mikhin commented on catalog.html
> +                <button type="submit" class="btn btn--gray sort-btn">Показать</button>
@Bakitov-Tilegen , не стал исправлять?)

2021-05-29 17:58 UTC, mikhin commented on catalog.html
> +          <h3 class="address-title">NЁRDS DESIGN STUDIO</h3>
@Bakitov-Tilegen , не стал исправлять?)

2021-05-29 17:58 UTC, mikhin commented on index.html
> +          <ul class="slider-list">
@Bakitov-Tilegen , не стал исправлять?)

2021-05-29 17:58 UTC, mikhin commented on index.html
> +                <a href="" class="btn btn--red service-link">Заказать</a>
@Bakitov-Tilegen , не стал исправлять?)

2021-05-29 17:58 UTC, mikhin commented on index.html
> +        <h2 class="vissible-title">О нас</h2>
vissible-title => visible-title

во-вторых не оч крутой нейминг — непонятный. Что значит «видимый заголовок»? Почему именно эту особенность нужно отразить в имени класса?

2021-05-29 17:58 UTC, mikhin commented on index.html
> +        <span class="about-us-title">Мы — маленькая, но гордая дизайн-студия из Краснодара.</span>
Наверно это все-таки тоже абзац, а не спан)

2021-05-30 02:15 UTC, Bakitov-Tilegen commented on catalog.html
> +                <ul class="sort-hedaer-list">
Простите 😣 но как вы замечаете опечатки я сам пишу это и не могу это увидеть постараюсь быть по внимательный

2021-05-30 03:18 UTC, Bakitov-Tilegen commented on catalog.html
> +                    <li class="sort-header-item">По типу</li>
🧐🧐🧐

2021-05-30 07:57 UTC, Bakitov-Tilegen commented on catalog.html
> +                        <legend></legend>
ok

2021-05-30 07:59 UTC, Bakitov-Tilegen commented on catalog.html
> +                        <legend><h3 class="radio-title">Сетка:</h3></legend>
ok

2021-06-01 03:10 UTC, Bakitov-Tilegen commented
что мне поставить на интерактивные элемент в голову ничего не приходить (((

2021-06-01 11:27 UTC, Bakitov-Tilegen reviewed
2 дз (главная + каталог) + 3 дз графика

2021-06-03 06:46 UTC, mikhin requested changes
@Bakitov-Tilegen , изображения делить по папкам в зависимости от места их употребления не нужно в данном случае, т.к. смысла в этом мало — если изображение из шапки вдруг начнет использоваться в подвале, то как тогда быть? Копировать в папку с изображениями для подвала? Или перемещать? Короче, переусложнение.

Пусть картинки просто лежат в одной папке единым списком.

2021-06-03 06:46 UTC, mikhin commented on Readme.md
> +* Наставник: `Неизвестно`.
@Bakitov-Tilegen , вот эти правки непонятные. Давай поправим?)

2021-06-03 06:46 UTC, mikhin commented on css/style.css
> +/*! Font */
Т.к. у нас не должно быть в этих заданиях стилизации, давай пока удалим этот файл совсем?

2021-06-03 13:49 UTC, Bakitov-Tilegen commented on Readme.md
> +* Наставник: `Неизвестно`.
ok
=

2021-06-03 13:50 UTC, Bakitov-Tilegen commented on css/style.css
> +/*! Font */
ok

2021-06-03 14:03 UTC, merged