Стилизация Главное страницы (шрифт и отступы)
htmlacademy-htmlcss/996491-nerds-31 pull request #5
Opened 2021-06-05 08:04 UTC by Bakitov-Tilegen

1) font-family,line-height, fw, fz, etc
2) margin padding btn
3) normalize.css
🧐🧐🧐🧐 кажется все

2021-06-09 07:02 UTC, mikhin requested changes

2021-06-09 07:02 UTC, mikhin commented on css/style.css
> +  border-left: 10px solid transparent;
Зачем нужны прозрачные границы толщиной в 10 пикселей?

2021-06-09 07:02 UTC, mikhin commented on css/style.css
> +
лишняя пустая строка

2021-06-09 07:02 UTC, mikhin commented on css/style.css
> +  padding: 0 0;
значение двух нулей можно сократить до одного)

2021-06-09 07:02 UTC, mikhin commented on css/style.css
> +
лишняя пустая строка

дальше подобных комментов про форматирование писать не буду) проверь пожалуйста все сам и сделай супер-аккуратно, чтобы было прям красиво и чисто все)

2021-06-09 07:02 UTC, mikhin commented on css/style.css
> +    width: 650px;
Что будет если убрать ширину? Для чего она нужна сейчас?

2021-06-09 23:50 UTC, Bakitov-Tilegen commented on css/style.css
> +    --font-size14: 14px;
😁😁😁 )))

2021-06-10 00:02 UTC, Bakitov-Tilegen commented on css/style.css
> +.btn {
ok

2021-06-10 00:27 UTC, Bakitov-Tilegen commented on css/style.css
> +    line-height: 1.125;
okay ✅

2021-06-10 00:29 UTC, Bakitov-Tilegen commented on css/style.css
> +.btn--yellow {
okay иногда забываю пользоваться beautify file )))

2021-06-10 00:32 UTC, Bakitov-Tilegen commented on css/style.css
> +  border-left: 10px solid transparent;
i dont know)

2021-06-10 00:34 UTC, Bakitov-Tilegen commented on css/style.css
> +  padding: 0 0;
facepalm😅😅😅😅 сори ))))

2021-06-10 00:36 UTC, Bakitov-Tilegen commented on css/style.css
> +
okay ✅  )))

2021-06-10 00:36 UTC, Bakitov-Tilegen commented on css/style.css
> +    width: 650px;
ok

2021-06-12 12:13 UTC, mikhin requested changes

2021-06-12 12:13 UTC, mikhin commented on css/style.css
> +  --font-size30: 30px;
Хм, вроде бы ничего не изменилось?

https://github.com/htmlacademy-htmlcss/996491-nerds-31/pull/5#discussion_r648019637

2021-06-12 12:13 UTC, mikhin commented on css/style.css
> +
Лишняя пустая строка. Давай наведем порядок с форматированием во всем документе?

2021-06-12 12:13 UTC, mikhin commented on css/style.css
> +
Не исправил

2021-06-13 11:14 UTC, mikhin requested changes

2021-06-13 11:14 UTC, mikhin commented on css/style.css
> +  --font-size30: 30px;
@Bakitov-Tilegen  вроде бы ничего не изменилось?

2021-06-13 11:14 UTC, mikhin commented on css/style.css
> +
Не исправил

2021-06-15 07:40 UTC, merged