Стилизация каталога
htmlacademy-htmlcss/996491-nerds-31 pull request #6
Opened 2021-06-15 15:42 UTC by Bakitov-Tilegen

2021-06-16 14:42 UTC, mikhin requested changes

2021-06-16 14:42 UTC, mikhin commented on css/style.css
> +  .header-title {
отступы все уехали. давай поправим?)

2021-06-16 14:42 UTC, mikhin commented on css/style.css
> +
лишняя строка

2021-06-16 14:42 UTC, mikhin commented on css/style.css
> +  .net-radio-item,
для .net-radio-item стили описаны и тут и выше — это непонятно. Давай переделаем?

2021-06-16 17:45 UTC, Bakitov-Tilegen commented on css/style.css
> +  .net-radio-item,
ok

2021-06-18 08:03 UTC, mikhin requested changes

2021-06-18 08:03 UTC, mikhin commented on css/style.css
> +  }
Скобка неправильно отформатирована. Давай поправим?)

2021-06-18 08:03 UTC, mikhin commented on css/style.css
> +  font-size: 55px;
Хм, нет, не так. Селекторы должны быть прижаты, а перед правилами должен быть отступ. Посмотри, как до этого у тебя в начале файла все оформлено?

2021-06-18 08:03 UTC, mikhin commented on css/style.css
> +  .nav-item:last-child {}
Пустые правила давай удалим?

2021-06-18 08:03 UTC, mikhin commented on css/style.css
> +  /* display: flex; */
Закоментированные правила давай удалим?)

2021-06-19 11:07 UTC, Bakitov-Tilegen commented on css/style.css
> +  /* display: flex; */
ok

2021-06-20 18:24 UTC, mikhin approved these changes

2021-06-20 18:24 UTC, merged