hw 5 Главное страницы
htmlacademy-htmlcss/996491-nerds-31 pull request #7
Opened 2021-06-21 09:02 UTC by Bakitov-Tilegen

Гриды и флексы

2021-06-23 09:39 UTC, mikhin requested changes
<img width="783" alt="Screenshot 2021-06-23 at 12 36 07" src="https://user-images.githubusercontent.com/38258318/123074041-a4ddb500-d41f-11eb-8dd5-3c390f4e420a.png">
<img width="1259" alt="Screenshot 2021-06-23 at 12 36 19" src="https://user-images.githubusercontent.com/38258318/123074057-a909d280-d41f-11eb-88c4-4b8cab6c8314.png">


@Bakitov-Tilegen , я вижу сейчас, что интерфейс как бы развален и не до конца собран. Если в данном пулл реквесте мы уже запилили и гриды и флексы, то уже должно стать очень близко к макету (пиксель перфект). Не совсем прям точь в точь, но сетки уже должны быть такими же как в макетах)

2021-06-23 16:16 UTC, Bakitov-Tilegen commented on css/style.css
> +
Окей

2021-06-23 16:16 UTC, Bakitov-Tilegen commented
Исправил

2021-06-28 14:01 UTC, mikhin commented
Уже гораздо лучше, но чисто по сеткам есть еще замечания:

1. Этот диалог по умолчанию должен быть скрыт. Плюс он должен по умолчанию быть отцентрован.
![Screenshot 2021-06-28 at 16 58 59](https://user-images.githubusercontent.com/38258318/123649256-486d0200-d832-11eb-9674-fa36f1bca7d2.png)

2. Футер должен быть отцентрован.
![Screenshot 2021-06-28 at 16 59 06](https://user-images.githubusercontent.com/38258318/123649261-49059880-d832-11eb-9326-29afee38c0c3.png)

3. Слайды в слайдере по умолчанию должны быть скрыты, кроме первого слайда. Плюс что-то не то с картинками.
![Screenshot 2021-06-28 at 16 58 41](https://user-images.githubusercontent.com/38258318/123649241-473bd500-d832-11eb-840a-8d758ab8a5c0.png)

4. Что-то не то с картинкой.
![Screenshot 2021-06-28 at 16 58 48](https://user-images.githubusercontent.com/38258318/123649250-486d0200-d832-11eb-80c2-b24f5d199dfc.png)

2021-06-28 14:02 UTC, mikhin requested changes

2021-07-01 09:02 UTC, merged